//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderThumbnailExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Loc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Loc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FolderThumbnailExplorer.Localization.Loc", typeof(Loc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add favorites to group.
        /// </summary>
        public static string Add2FavGroup {
            get {
                return ResourceManager.GetString("Add2FavGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to group:.
        /// </summary>
        public static string Add2Group {
            get {
                return ResourceManager.GetString("Add2Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add current folder to Favorites..
        /// </summary>
        public static string AddNewFavBtnTT {
            get {
                return ResourceManager.GetString("AddNewFavBtnTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new favorites.
        /// </summary>
        public static string AddNewFavTitle {
            get {
                return ResourceManager.GetString("AddNewFavTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Name.
        /// </summary>
        public static string ANFName {
            get {
                return ResourceManager.GetString("ANFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Path.
        /// </summary>
        public static string ANFPath {
            get {
                return ResourceManager.GetString("ANFPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ANFSave {
            get {
                return ResourceManager.GetString("ANFSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Up
        ///You can also use &lt;Backspace&gt; to go up..
        /// </summary>
        public static string GoUpBtnTT {
            get {
                return ResourceManager.GetString("GoUpBtnTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder has subfolder(s)..
        /// </summary>
        public static string HasSubfolderTT {
            get {
                return ResourceManager.GetString("HasSubfolderTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Click on normal folder - Advance folder.
        ///Left Click on thumbnailed folder - Open Photo Viewer.
        ///Right Click on any folder - Open in Explorer.
        ///Double Click on any folder&apos;s name - Advance folder.
        ///Ctrl+F2 - Random image folder..
        /// </summary>
        public static string MainToolTip {
            get {
                return ResourceManager.GetString("MainToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ℹ Quick Tip.
        /// </summary>
        public static string MainToolTipTitle {
            get {
                return ResourceManager.GetString("MainToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or create a new group:.
        /// </summary>
        public static string OrNewGroup {
            get {
                return ResourceManager.GetString("OrNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to move the window..
        /// </summary>
        public static string PhotoViewerTitleBarTT {
            get {
                return ResourceManager.GetString("PhotoViewerTitleBarTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Close the window.
        /// </summary>
        public static string PVCloseTT {
            get {
                return ResourceManager.GetString("PVCloseTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to resize..
        /// </summary>
        public static string PVGridSplitterTT {
            get {
                return ResourceManager.GetString("PVGridSplitterTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Maximize or Restore the window.
        /// </summary>
        public static string PVMaxTT {
            get {
                return ResourceManager.GetString("PVMaxTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Minimize the window.
        /// </summary>
        public static string PVMinTT {
            get {
                return ResourceManager.GetString("PVMinTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always On Top.
        /// </summary>
        public static string PVPopUpSettingsAOT {
            get {
                return ResourceManager.GetString("PVPopUpSettingsAOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Load Threshold.
        /// </summary>
        public static string PVPopUpSettingsLoadThreshold {
            get {
                return ResourceManager.GetString("PVPopUpSettingsLoadThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls how many images to load in a single batch.
        ///Select the last image in list to continue loading..
        /// </summary>
        public static string PVPopUpSettingsLoadThresholdTT {
            get {
                return ResourceManager.GetString("PVPopUpSettingsLoadThresholdTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save window position &amp; size.
        /// </summary>
        public static string PVPopUpSettingsSavePos {
            get {
                return ResourceManager.GetString("PVPopUpSettingsSavePos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Photo Viewer&apos;s position &amp; size so it will be spawned at your desired location.
        ///The setting file is in [%USERPROFILE%\AppData\Local\%USERNAME%].
        ///Right click the button to reset 480*600@(0,0)..
        /// </summary>
        public static string PVPopUpSettingsSavePosTT {
            get {
                return ResourceManager.GetString("PVPopUpSettingsSavePosTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll view the image.
        /// </summary>
        public static string PVPopUpSettingsScrView {
            get {
                return ResourceManager.GetString("PVPopUpSettingsScrView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By enabling this, Slideshow and Twin-Page viewing option will be ignored..
        /// </summary>
        public static string PVPopUpSettingsScrViewTT {
            get {
                return ResourceManager.GetString("PVPopUpSettingsScrViewTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide show interval.
        /// </summary>
        public static string PVPopUpSettingsSlideshowInterval {
            get {
                return ResourceManager.GetString("PVPopUpSettingsSlideshowInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milliseconds to wait before switching images.
        ///You can also use mouse wheel on this.
        ///Negative value = Reverse order..
        /// </summary>
        public static string PVPopUpSettingsSlideshowValue {
            get {
                return ResourceManager.GetString("PVPopUpSettingsSlideshowValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please give me a short number between -32768~32767.
        ///Also, don&apos;t give me zeros..
        /// </summary>
        public static string PVPopUpSettingsSlideshowValueError {
            get {
                return ResourceManager.GetString("PVPopUpSettingsSlideshowValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙ Settings.
        /// </summary>
        public static string PVPopUpSettingsTitle {
            get {
                return ResourceManager.GetString("PVPopUpSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twin-Page viewing.
        /// </summary>
        public static string PVPopUpSettingsTwin {
            get {
                return ResourceManager.GetString("PVPopUpSettingsTwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn two pages at a time.
        /// </summary>
        public static string PVPopUpSettingsTwinDoubleTurn {
            get {
                return ResourceManager.GetString("PVPopUpSettingsTwinDoubleTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normally you would use it under Twin-Page viewing mode..
        /// </summary>
        public static string PVPopUpSettingsTwinDoubleTurnTT {
            get {
                return ResourceManager.GetString("PVPopUpSettingsTwinDoubleTurnTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to Left.
        /// </summary>
        public static string PVPopUpSettingsTwinRightToLeft {
            get {
                return ResourceManager.GetString("PVPopUpSettingsTwinRightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, the current image is displayed on the left and the next image is displayed on the right.
        ///This flips that..
        /// </summary>
        public static string PVPopUpSettingsTwinRightToLeftTT {
            get {
                return ResourceManager.GetString("PVPopUpSettingsTwinRightToLeftTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Wheel on image - Next/Previous.
        ///Right Click + Mouse Wheel on image - Zoom &amp; Pan.
        ///Move Mouse while zoomed in - Pan Up &amp; Down.
        ///Esc - Close Photo Viewer..
        /// </summary>
        public static string PVToolTip {
            get {
                return ResourceManager.GetString("PVToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔄 Refresh.
        /// </summary>
        public static string RefreshDriveBtn {
            get {
                return ResourceManager.GetString("RefreshDriveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh logical drives list..
        /// </summary>
        public static string RefreshDriveBtnTT {
            get {
                return ResourceManager.GetString("RefreshDriveBtnTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the view..
        /// </summary>
        public static string RefreshViewTT {
            get {
                return ResourceManager.GetString("RefreshViewTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group exists and will be replaced, continue?.
        /// </summary>
        public static string ReplaceGroup {
            get {
                return ResourceManager.GetString("ReplaceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group exists!.
        /// </summary>
        public static string ReplaceGroupCaption {
            get {
                return ResourceManager.GetString("ReplaceGroupCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize the thumbnail..
        /// </summary>
        public static string ScaleSliderTT {
            get {
                return ResourceManager.GetString("ScaleSliderTT", resourceCulture);
            }
        }
    }
}
