//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderThumbnailExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Loc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Loc() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FolderThumbnailExplorer.Localization.Loc", typeof(Loc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add current folder to Favorites. 的本地化字符串。
        /// </summary>
        public static string AddNewFavBtnTT {
            get {
                return ResourceManager.GetString("AddNewFavBtnTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add new favorites. 的本地化字符串。
        /// </summary>
        public static string AddNewFavTitle {
            get {
                return ResourceManager.GetString("AddNewFavTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Name 的本地化字符串。
        /// </summary>
        public static string ANFName {
            get {
                return ResourceManager.GetString("ANFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Path 的本地化字符串。
        /// </summary>
        public static string ANFPath {
            get {
                return ResourceManager.GetString("ANFPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string ANFSave {
            get {
                return ResourceManager.GetString("ANFSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go Up
        ///You can also use &lt;Backspace&gt; to go up. 的本地化字符串。
        /// </summary>
        public static string GoUpBtnTT {
            get {
                return ResourceManager.GetString("GoUpBtnTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This folder has subfolder(s). 的本地化字符串。
        /// </summary>
        public static string HasSubfolderTT {
            get {
                return ResourceManager.GetString("HasSubfolderTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left Click on normal folder - Advance folder.
        ///Left Click on thumbnailed folder - Open Photo Viewer.
        ///Right Click on any folder - Open in Explorer.
        ///Double Click on any folder&apos;s name - Advance folder. 的本地化字符串。
        /// </summary>
        public static string MainToolTip {
            get {
                return ResourceManager.GetString("MainToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ℹ Quick Tip 的本地化字符串。
        /// </summary>
        public static string MainToolTipTitle {
            get {
                return ResourceManager.GetString("MainToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag to move the window. 的本地化字符串。
        /// </summary>
        public static string PhotoViewerTitleBarTT {
            get {
                return ResourceManager.GetString("PhotoViewerTitleBarTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .Close the window 的本地化字符串。
        /// </summary>
        public static string PVCloseTT {
            get {
                return ResourceManager.GetString("PVCloseTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag to resize. 的本地化字符串。
        /// </summary>
        public static string PVGridSplitterTT {
            get {
                return ResourceManager.GetString("PVGridSplitterTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .Maximize or Restore the window 的本地化字符串。
        /// </summary>
        public static string PVMaxTT {
            get {
                return ResourceManager.GetString("PVMaxTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .Minimize the window 的本地化字符串。
        /// </summary>
        public static string PVMinTT {
            get {
                return ResourceManager.GetString("PVMinTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slide show interval 的本地化字符串。
        /// </summary>
        public static string PVPopUpSettingsSlideshowInterval {
            get {
                return ResourceManager.GetString("PVPopUpSettingsSlideshowInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Milliseconds to wait before switching images.
        ///You can also use mouse wheel on this.
        ///Negative value = Reverse order. 的本地化字符串。
        /// </summary>
        public static string PVPopUpSettingsSlideshowValue {
            get {
                return ResourceManager.GetString("PVPopUpSettingsSlideshowValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please give me a short number between -32768~32767.
        ///Also, don&apos;t give me zeros. 的本地化字符串。
        /// </summary>
        public static string PVPopUpSettingsSlideshowValueError {
            get {
                return ResourceManager.GetString("PVPopUpSettingsSlideshowValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ⚙ Settings 的本地化字符串。
        /// </summary>
        public static string PVPopUpSettingsTitle {
            get {
                return ResourceManager.GetString("PVPopUpSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse Wheel on image - Next/Previous.
        ///Right Click + Mouse Wheel on image - Zoom &amp; Pan.
        ///Move Mouse while zoomed in - Pan Up &amp; Down.
        ///Esc - Close Photo Viewer. 的本地化字符串。
        /// </summary>
        public static string PVToolTip {
            get {
                return ResourceManager.GetString("PVToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 🔄 Refresh 的本地化字符串。
        /// </summary>
        public static string RefreshDriveBtn {
            get {
                return ResourceManager.GetString("RefreshDriveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh logical drives list.
        ///Doesn&apos;t work for some reason. 的本地化字符串。
        /// </summary>
        public static string RefreshDriveBtnTT {
            get {
                return ResourceManager.GetString("RefreshDriveBtnTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh the view. 的本地化字符串。
        /// </summary>
        public static string RefreshViewTT {
            get {
                return ResourceManager.GetString("RefreshViewTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resize the thumbnail. 的本地化字符串。
        /// </summary>
        public static string ScaleSliderTT {
            get {
                return ResourceManager.GetString("ScaleSliderTT", resourceCulture);
            }
        }
    }
}
